Install with conan doc pages
brainboxdotcc/DPP pull request #1070
Opened 2024-01-26 15:02 UTC by MikeRavenelle

Documentation for conan support.

- Added conan install documentation and modified section to include it.

## Documentation change checklist

- [ X] My documentation changes follow the [docs style guide](https://dpp.dev/docs-standards.html) and any code examples follow the [coding style guide](https://dpp.dev/coding-standards.html).
- [X] I tested that my change works before raising the PR (via running `doxygen`, and testing examples).
- [X] I have not moved any existing pages or changed any existing URLs without strong justification as to why.
- [X] I have not generated content using AI or a desktop utility such as grammarly.

2024-01-26 19:03 UTC, braindigitalis commented
reopened and targeted at dev

2024-01-26 19:04 UTC, braindigitalis approved these changes
good to go as soon as Conan is live 👍

2024-03-28 16:57 UTC, Jaskowicz1 commented
Renamed PR to correctly align with our conventions

2024-03-28 16:57 UTC, Jaskowicz1 commented
Renamed this PR to correctly align with our conventions.

2024-03-28 17:26 UTC, Jaskowicz1 requested changes

2024-03-28 17:26 UTC, Jaskowicz1 commented on docpages/install/install-conan.md
> +conan install .. --build=missing -of=. -s build_type=Release
This doesn't work on Windows. It seems you can't specify the path if you have `-of=.`.

Doing `conan install .. --build=missing -s build_type=Debug` seems to fix this.

2024-03-28 21:37 UTC, Jaskowicz1 commented on docpages/install/install-conan.md
> +conan install .. --build=missing -of=. -s build_type=Release
Hm, you do need the `-of=` so I would maybe change that to just be the current path.

2024-03-29 00:09 UTC, Jaskowicz1 commented on docpages/install/install-conan.md
> +conan install .. --build=missing -of=. -s build_type=Release
Scrap that, I would change this entire thing to be something like the following:
```bash
mkdir build
conan install . --output-folder=build --build=missing -s build_type=Release
cd build
cmake .. -DCMAKE_TOOLCHAIN_FILE="conan_toolchain.cmake"
cmake --build build -j8 --config Release
```

2024-10-30 19:03 UTC, merged