big number implementation, for future use in permissions bitfields
brainboxdotcc/DPP pull request #1176
Opened 2024-06-19 19:32 UTC by braindigitalis

Officially, the Discord documentation says that permission values can be any arbitrary number of digits. At time of writing there are only 50 bits of permissions, but this is set to grow larger and potentially past 64 bits. They will continue to send this data as a huge single integer at that point, because this is obviously sensible. **/s**
 
dpp::bignumber uses OpenSSL BN_* under the hood, as we include openssl anyway for HTTPS.

## Code change checklist

- [x] I have ensured that all methods and functions are **fully documented** using doxygen style comments.
- [x] My code follows the [coding style guide](https://dpp.dev/coding-standards.html).
- [x] I tested that my change works before raising the PR.
- [x] I have ensured that I did not break any existing API calls.
- [x] I have not built my pull request using AI, a static analysis tool or similar without any human oversight.

2024-06-19 22:43 UTC, Jaskowicz1 approved these changes

2024-06-20 00:13 UTC, Mishura4 requested changes

2024-06-20 00:13 UTC, Mishura4 commented on src/dpp/bignum.cpp
> +	BN_bin2bn((unsigned char *)bits.data(), bits.size() * sizeof(uint64_t), ssl_bn->bn);
Please just use reinterpret_cast here, easier to `grep` 😄

2024-06-20 00:13 UTC, Mishura4 commented on src/dpp/bignum.cpp
> +	auto size_64_bit = (std::size_t)ceil((double)size / sizeof(uint64_t));
static_cast please!

2024-06-20 00:13 UTC, Mishura4 commented on src/dpp/bignum.cpp
> +	BN_bn2binpad(ssl_bn->bn, (unsigned char*)returned.data(), returned.size() * sizeof(uint64_t));
We must reinterpret the cast

2024-06-20 12:24 UTC, Mishura4 approved these changes

2024-06-20 12:25 UTC, merged