feat: commandhandler now has functions to edit/get/delete responses
brainboxdotcc/DPP pull request #1199
Opened 2024-07-14 12:34 UTC by Jaskowicz1

This PR adds functions to `dpp::commandhandler` to allow users to edit, get, and delete, responses. Whilst `dpp::commandhandler` is deprecated, we still have a good few people using it.

## Code change checklist

- [x] I have ensured that all methods and functions are **fully documented** using doxygen style comments.
- [x] My code follows the [coding style guide](https://dpp.dev/coding-standards.html).
- [ ] I tested that my change works before raising the PR.
- [x] I have ensured that I did not break any existing API calls.
- [x] I have not built my pull request using AI, a static analysis tool or similar without any human oversight.

2024-07-16 22:09 UTC, braindigitalis requested changes

2024-07-16 22:09 UTC, braindigitalis commented on src/dpp/commandhandler.cpp
> +void commandhandler::edit_response(const message &m, command_source source, command_completion_event_t callback) {
these all need a check like in thinking, e.g.:

```cpp
if (!source.command_token.empty() && source.command_id) {
```

they cant do anything if its a message command.

2024-07-16 22:09 UTC, braindigitalis commented on src/dpp/commandhandler.cpp
> +void commandhandler::edit_original_response(const message &m, command_source source, command_completion_event_t callback) {
if we're adding these, shouldnt they also work for message commands?

this is the point of commandhandler, and why we dont really add much to it

2024-08-09 08:40 UTC, braindigitalis commented
any movement on this?

2024-10-08 18:42 UTC, Jaskowicz1 commented
Closing, we are officially deprecating command handler so we should not support new features.

2024-10-08 18:42 UTC, closed without merging