Remove coroutine/DPP_CORO experimental warnings
brainboxdotcc/DPP pull request #1221
Opened 2024-08-12 12:17 UTC by DJOetzi

Removed notices of coroutines being an experimental feature.

## Documentation change checklist

- [ X ] My documentation changes follow the [docs style guide](https://dpp.dev/docs-standards.html) and any code examples follow the [coding style guide](https://dpp.dev/coding-standards.html).
- [ X ] I tested that my change works before raising the PR (via running `doxygen`, and testing examples).
- [ X ] I have not moved any existing pages or changed any existing URLs without strong justification as to why.
- [ X ] I have not generated content using AI or a desktop utility such as grammarly.

2024-08-12 12:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/brainboxdotcc/DPP?pullRequest=1221) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/brainboxdotcc/DPP?pullRequest=1221) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/brainboxdotcc/DPP?pullRequest=1221) it.</sub>

2024-08-12 12:43 UTC, braindigitalis approved these changes

2024-08-12 22:10 UTC, Jaskowicz1 requested changes
You're missing https://github.com/brainboxdotcc/DPP/blob/ced36fd7652ed24ec3784cbc150722a1e5f6456a/include/dpp/coro/job.h#L48

https://github.com/brainboxdotcc/DPP/blob/ced36fd7652ed24ec3784cbc150722a1e5f6456a/include/dpp/coro/async.h#L103

https://github.com/brainboxdotcc/DPP/blob/ced36fd7652ed24ec3784cbc150722a1e5f6456a/library/CMakeLists.txt#L292 (just remove the word "experimental" here, keep the `message()`).

https://github.com/brainboxdotcc/DPP/blob/ced36fd7652ed24ec3784cbc150722a1e5f6456a/include/dpp/coro/task.h#L87

https://github.com/brainboxdotcc/DPP/blob/ced36fd7652ed24ec3784cbc150722a1e5f6456a/include/dpp/coro/coroutine.h#L67

2024-08-12 22:10 UTC, Jaskowicz1 commented on docpages/example_programs/using_coroutines.md
> -\include{doc} coro_warn.dox
The `coro_warn.dox` needs to stay. People needs to know that Coro is only supported on certain compiler versions. Just remove the last part of the `coro_warn.dox` :)

2024-08-30 09:40 UTC, Jaskowicz1 commented
Any update on this?

2024-09-04 15:34 UTC, DJOetzi commented
> You're missing
> 
> https://github.com/brainboxdotcc/DPP/blob/ced36fd7652ed24ec3784cbc150722a1e5f6456a/include/dpp/coro/job.h#L48
> 
> https://github.com/brainboxdotcc/DPP/blob/ced36fd7652ed24ec3784cbc150722a1e5f6456a/include/dpp/coro/async.h#L103
> 
> https://github.com/brainboxdotcc/DPP/blob/ced36fd7652ed24ec3784cbc150722a1e5f6456a/library/CMakeLists.txt#L292
> 
> (just remove the word "experimental" here, keep the `message()`).
> https://github.com/brainboxdotcc/DPP/blob/ced36fd7652ed24ec3784cbc150722a1e5f6456a/include/dpp/coro/task.h#L87
> 
> https://github.com/brainboxdotcc/DPP/blob/ced36fd7652ed24ec3784cbc150722a1e5f6456a/include/dpp/coro/coroutine.h#L67

should I just remove these comments altogether?

2024-09-28 20:17 UTC, Jaskowicz1 approved these changes

2024-09-29 15:28 UTC, merged