Feat: Implementing named commands handlers for the cluster
brainboxdotcc/DPP pull request #1262
Opened 2024-10-07 22:58 UTC by ruslan-ilesik

[ Please outline your change here. Be sure to check the checkboxes below. ]

## Code change checklist

- [X] I have ensured that all methods and functions are **fully documented** using doxygen style comments.
- [X] My code follows the [coding style guide](https://dpp.dev/coding-standards.html).
- [ ] I tested that my change works before raising the PR.
- [ ] I have ensured that I did not break any existing API calls.
- [X] I have not built my pull request using AI, a static analysis tool or similar without any human oversight.

at this point it is draft pr to get feedback. i hope to test it tomorrow.

2024-10-08 00:27 UTC, Jaskowicz1 commented
Moved to draft, please don't write text below checklist, just replace the [ please outline ] box with that (along with a desc)!

2024-10-08 05:43 UTC, braindigitalis commented on include/dpp/cluster.h
> +
your editor has been doing automatic tidyips of the file, you should probably turn this feature off as it will make it harder to review your prs

2024-10-08 05:46 UTC, braindigitalis commented
looks good to me but far too much random formatting changes all over cluster.h that makes it hard to read.
how well does the new feature work?

2024-10-08 12:36 UTC, ruslan-ilesik commented
Checked it with c++20 and it works in both scenarios of regular and coroutine based handlers. also removing handler while it gets executed also works as supposed

2024-10-08 12:46 UTC, ruslan-ilesik commented
c++17 also work fine for me

Note: all the tests were done on WSL ubuntu 20.04 using clang++19

2024-10-08 18:40 UTC, Jaskowicz1 requested changes

2024-10-08 18:43 UTC, ruslan-ilesik commented on include/dpp/cluster.h
> +
is it even possible to revert?

2024-10-08 18:44 UTC, Jaskowicz1 commented on include/dpp/cluster.h
> +
Yes, just fix your IDE, copy your changes, revert the change (locally), redo your changes, submit in new commit.

2024-10-08 20:28 UTC, ruslan-ilesik commented
note, this PR is not done yet as we found issues with function semantics

2024-10-08 20:53 UTC, ruslan-ilesik commented
This is working solution. Tested on both c++17 dpp builds and c++20

WSL ubuntu 20:04 clang++-19

2024-10-08 21:03 UTC, Jaskowicz1 requested changes

2024-10-08 21:03 UTC, Jaskowicz1 commented on src/dpp/cluster.cpp
> +			 co_return;  // Command not found
Comment doesn't follow code code convention

2024-10-08 21:03 UTC, Jaskowicz1 commented on src/dpp/cluster.cpp
> +			 return;  // Command not found
Ditto

2024-10-08 21:29 UTC, braindigitalis approved these changes

2024-10-08 21:58 UTC, Mishura4 requested changes
Nice work! Just one minor thing

2024-10-08 21:58 UTC, Mishura4 commented on include/dpp/cluster.h
> +		named_commands.emplace(name, handler);
Why not
```cpp
auto [_, inserted] = named_commands.try_emplace(name, handler);
return inserted;
```
Saves the double lookup, and actually, should std::forward handler here too

2024-10-08 21:58 UTC, Mishura4 commented on src/dpp/cluster.cpp
> +	named_commands.emplace(name, handler);
Same here as my other comment

2024-10-08 23:10 UTC, Mishura4 approved these changes

2024-10-09 06:08 UTC, Jaskowicz1 approved these changes

2024-10-09 09:58 UTC, merged