Added example of how to invite a bot
brainboxdotcc/DPP pull request #164
Opened 2021-12-04 11:36 UTC by Commandserver

- added the example
- and reformatted a little of the index site.

2021-12-04 11:40 UTC, Commandserver commented
btw should i use `“` or `"`?

2021-12-04 11:53 UTC, SirObby commented
In what context?

2021-12-04 11:53 UTC, SirObby commented
Just use `"`'s

2021-12-04 12:02 UTC, Commandserver commented
> Just use `"`'s

ok

2021-12-04 23:24 UTC, braindigitalis requested changes

2021-12-04 23:24 UTC, braindigitalis commented on docpages/INDEX.md
> -* [Discord Server](https://discord.gg/dpp)
I like the PR but I don't think this change below is needed?
it just shortens the links which harms SEO

2021-12-04 23:35 UTC, Commandserver commented
okay. changed back

2021-12-05 08:41 UTC, braindigitalis approved these changes

2021-12-05 08:41 UTC, merged