fix: emoji::format didn't return animated emojis
brainboxdotcc/DPP pull request #242
Opened 2022-01-27 07:58 UTC by Commandserver

2022-01-27 17:54 UTC, Commandserver commented
I've tested the added `role_edit_positions` method for functionality

2022-01-27 20:40 UTC, braindigitalis requested changes

2022-01-27 20:40 UTC, braindigitalis commented on include/dpp/cluster.h
> +	 * Modify the position of a role. Requires the `MANAGE_ROLES` permission.
instead of doing this the function should be fixed to accept multiple roles like the API call it connects to

2022-01-29 14:57 UTC, braindigitalis approved these changes

2022-01-29 14:57 UTC, merged