Start slash command permission
brainboxdotcc/DPP pull request #28
Opened 2021-05-25 21:51 UTC by d-nery

This starts slash command permission management

Permissions only applies in guild commands, so I modified the guild_create_command to also send the guild_command_edit_permission after it has completed succesfully

Relevant docs: https://discord.com/developers/docs/interactions/slash-commands#get-guild-application-command-permissions

2021-05-25 23:24 UTC, braindigitalis commented on include/dpp/slashcommand.h
> +	snowflake id;
not needed, managed::id already defines this field

2021-05-25 23:31 UTC, braindigitalis requested changes
looks good except for duplicated id member variable in slashcommand class

2021-06-14 05:50 UTC, webtax-gh commented
@d-nery is this still a draft 🚧, or is it ready 😄! Code looks good and it's ready to merge if you want to.

2021-06-14 17:10 UTC, d-nery commented
I'll do some final checks, get the lasat changes from dev and solve conflicts, and then I remove draft

2021-07-24 20:20 UTC, braindigitalis commented
is this ready to merge in now? seemed a simple commit

2021-07-26 09:33 UTC, braindigitalis approved these changes

2021-07-26 09:33 UTC, merged