fix typos and trailing spaces
brainboxdotcc/DPP pull request #284
Opened 2022-02-17 16:31 UTC by es183923

This PR removes trailing spaces from the entire library, and also fixes some typos, including an enum, and a variable.

2022-02-17 17:32 UTC, braindigitalis commented
this pr is scary massive, not sure how to merge it without it conflicting with other changes in progress rn...

2022-02-17 17:48 UTC, es183923 commented
I've removed the change for removing trailing fixes.

2022-02-19 09:52 UTC, braindigitalis requested changes

2022-02-19 09:52 UTC, braindigitalis commented on include/dpp/user.h
> +	u_house_ =		0b00000000001000000000000,
u_house what exactly 😂

2022-02-19 09:52 UTC, braindigitalis commented on include/dpp/user.h
> +	bool is_house_() const;
hooooooose

2022-02-20 09:24 UTC, braindigitalis commented
any progress on this? just needs u_house_ fixing and it can be merged in

2022-02-20 19:00 UTC, merged