fix verb placement for dpp::cluster
brainboxdotcc/DPP pull request #292
Opened 2022-02-20 15:58 UTC by es183923

2022-02-20 17:42 UTC, braindigitalis requested changes

2022-02-20 17:42 UTC, braindigitalis commented on include/dpp/dispatcher.h
> -struct DPP_EXPORT message_delete_bulk_t : public event_dispatch_t {
please dont change these!
just the cluster:: methods for REST calls...

2022-02-20 23:01 UTC, braindigitalis approved these changes

2022-02-21 19:26 UTC, Commandserver commented
could you also rename `guild_member_delete` to something else than delete. The name doesn't sound like the method will kick a member tbh. e.g. `guild_member_remove`. Same for `guild_member_delete_role`, and yep, this one doesn't delete roles lol.

2022-02-22 00:38 UTC, es183923 commented
This PR only moves the words around. If you feel that the words should be changed, make a separate issue or PR.

2022-03-26 17:27 UTC, closed without merging