break: remove co_attach & enforce event handler call semantics (return void/dpp::job, take const event)
brainboxdotcc/DPP pull request #807
Opened 2023-08-25 19:38 UTC by Mishura4

- [x] My pull request is made against the `dev` branch.
- [x] I have ensured that the changed library can be built on your target system. I did not introduce any platform-specific code.
- [x] I have ensured that all methods and functions are **fully documented** using doxygen style comments.
- [x] I tested my commits, by adding a test case to the unit tests if needed
- [x] I have ensured that I did not break any existing API calls.
- [x] My code follows the [coding style guide](https://dpp.dev/coding-standards.html) (if you are not sure, match the code style of existing files including indent style etc).
- [x] I have not built my pull request using AI, a static analysis tool or similar without any human oversight. Where I have generated this pull request using a tool, I have justified why this is needed.

2023-08-26 01:42 UTC, braindigitalis requested changes
don't the coro docs need to be updated to reflect this change? please dismiss review if this will be a separate pr

2023-08-26 01:48 UTC, Mishura4 commented
TRUE i forgor, nice catch. Will update tomorrow

2023-08-26 13:48 UTC, Mishura4 commented
Updated [the docs](https://deploy-preview-807--dpp-dev.netlify.app/coroutines)

2023-08-26 14:05 UTC, Mishura4 commented
This will likely conflict with #808 as well, if it's merged first I'll resolve them on my end

2023-08-26 20:12 UTC, Commandserver approved these changes

2023-08-27 07:12 UTC, braindigitalis approved these changes

2023-08-28 03:07 UTC, merged