docs: new cache example and file name fixes
brainboxdotcc/DPP pull request #862
Opened 2023-09-18 13:23 UTC by professor91

- Added example for using cache
- Replaced - with _ in filenames and updated in respective md files
- Moved permissions example md file of Misc category to /misc dir

- [x] My pull request is made against the `dev` branch.
- [x] I have ensured that the changed library can be built on your target system. I did not introduce any platform-specific code.
- [x] I have ensured that all methods and functions are **fully documented** using doxygen style comments.
- [x] I tested my commits, by adding a test case to the unit tests if needed
- [x] I have ensured that I did not break any existing API calls.
- [x] My code follows the [coding style guide](https://dpp.dev/coding-standards.html) (if you are not sure, match the code style of existing files including indent style etc).
- [x] I have not built my pull request using AI, a static analysis tool or similar without any human oversight. Where I have generated this pull request using a tool, I have justified why this is needed.

2023-09-18 13:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/brainboxdotcc/DPP?pullRequest=862) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/brainboxdotcc/DPP?pullRequest=862) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/brainboxdotcc/DPP?pullRequest=862) it.</sub>

2023-09-18 14:16 UTC, braindigitalis requested changes
not sure there's any need to rename all the images apart from that looks good 👍

2023-09-18 15:46 UTC, professor91 commented
updated

2023-09-18 15:51 UTC, Jaskowicz1 commented on docpages/example_programs/the_basics/using_cache.md
> +- `dpp::find_guild_member()`
Needs a new line after this!

2023-09-18 17:39 UTC, braindigitalis requested changes
can you please also revert the name changes of the markdown files?
they don't need to be changed

2023-09-19 04:01 UTC, professor91 commented
> can you please also revert the name changes of the markdown files? they don't need to be changed

i changed so they'd in consistent format...the links don't change if that's your concern, lmk if they still need to be revert back

2023-09-20 02:12 UTC, braindigitalis commented
> > can you please also revert the name changes of the markdown files? they don't need to be changed
> 
> i changed so they'd in consistent format...the links don't change if that's your concern, lmk if they still need to be revert back

yeah please revert those as it makes the PR shorter

2023-09-20 04:48 UTC, professor91 commented
added new line and reverted markdown filenames

2023-09-20 07:10 UTC, braindigitalis commented on docpages/example_programs/the_basics/using_cache.md
> +@note As of August 30th, 2022, Discord made Guild Members a privileged intent. You must have GUILD_MEMBERS intent enabled for your app from discord developers portal to be able to look for members in
this isn't technically true, id you don't have the intent the cache will "trickle fill" slowly with members as the bot sees them, e.g. when they send a message, join a VC, or send a slash command. you might also want to mention how slash commands have resolved sets that eliminates the need to look in the cache for data.

2023-09-20 10:41 UTC, braindigitalis approved these changes

2023-09-20 16:08 UTC, merged