feat: added message_author_id field to message_reaction_add_t event
brainboxdotcc/DPP pull request #889
Opened 2023-09-24 19:32 UTC by Commandserver

## Code change checklist

- [x] I have ensured that all methods and functions are **fully documented** using doxygen style comments.
- [ ] My code follows the [coding style guide](https://dpp.dev/coding-standards.html).
- [ ] I tested that my change works before raising the PR.
- [ ] I have ensured that I did not break any existing API calls.
- [x] I have not built my pull request using AI, a static analysis tool or similar without any human oversight.

2023-09-25 09:05 UTC, Jaskowicz1 commented on src/dpp/user.cpp
> +											  "avatar-decorations/" + std::to_string(this->id), this->avatar_decoration.to_string(),
indentation?

2023-09-25 09:05 UTC, Jaskowicz1 commented
Wait, 4 commits from here are in #732 .
How has GitHub not picked up on this?

2023-09-25 10:11 UTC, braindigitalis commented
> Wait, 4 commits from here are in #732 . How has GitHub not picked up on this?

It's just a difference in history between branches, it'll iron out in the merge

2023-09-25 10:13 UTC, Jaskowicz1 commented
> > Wait, 4 commits from here are in #732 . How has GitHub not picked up on this?
> 
> It's just a difference in history between branches, it'll iron out in the merge

Ah right 👍

2023-09-25 15:21 UTC, Commandserver commented
Oopsy whoopsy

2023-09-25 15:32 UTC, Mishura4 approved these changes

2023-10-07 14:42 UTC, braindigitalis commented
is this ready at all?

2023-10-14 13:19 UTC, Jaskowicz1 commented
I've renamed this PR from `feat: added message_author_id field to message_reaction_add_t event` to `feat: added component default values`. I'll also test this and see if this good to go 👍

2023-10-14 13:56 UTC, Jaskowicz1 requested changes

2023-10-14 13:56 UTC, Jaskowicz1 commented on src/dpp/message.cpp
> +				o["type"] = v.type;
This isn't right, discord doesn't take an int for the type but rather a string. Change `o["type"] = v.type;` to be something like this:

```c++
if(v.type == dpp::cdt_role) {
	o["type"] = "role";
} else if(v.type == dpp::cdt_channel) {
	o["type"] = "channel";
} else if(v.type == dpp::cdt_user) {
	o["type"] = "user";
}
```

2023-10-14 13:56 UTC, Jaskowicz1 commented on src/dpp/message.cpp
> +				o["type"] = v.type;
ditto comment on line 361

2023-10-16 16:28 UTC, braindigitalis commented
i have ticked the boxes in the pr, and added archies changes to merge this, as i need it in my own projects.

2023-10-16 16:44 UTC, merged