feat: dpp::application is now updated, added set_iconhash_not_null
brainboxdotcc/DPP pull request #953
Opened 2023-10-18 20:59 UTC by Jaskowicz1

This PR now updates dpp::application, making it up-to-date (and even have content discord doesn't document yet). It also adds `set_iconhash_not_null`, meaning we don't have to do workarounds to set the iconhash as it can be set from a string.

## Code change checklist

- [x] I have ensured that all methods and functions are **fully documented** using doxygen style comments.
- [x] My code follows the [coding style guide](https://dpp.dev/coding-standards.html).
- [x] I tested that my change works before raising the PR.
- [x] I have ensured that I did not break any existing API calls.
- [x] I have not built my pull request using AI, a static analysis tool or similar without any human oversight.

2023-10-18 21:04 UTC, braindigitalis requested changes

2023-10-18 21:04 UTC, braindigitalis commented on src/dpp/application.cpp
> +	if (!this->cover_image.to_string().empty()) {
the id is required here, as it is used in the url, else youll have app-icons/0/xxxxxx

2023-10-19 08:21 UTC, Jaskowicz1 commented
Some of the new data I have added seems to maybe be in relation to [this update, adding premium subscriptions in the US](https://discord.com/developers/docs/change-log#premium-app-subscriptions-available-in-the-us). However, the data is still undocumented and this update doesn't say anything about that data at all.

2023-10-19 09:02 UTC, braindigitalis approved these changes

2023-10-19 09:02 UTC, merged