refactor: changed the way messages holds files
brainboxdotcc/DPP pull request #999
Opened 2023-11-06 21:20 UTC by Jaskowicz1

This PR changes the way that messages hold files. Rather than there being 3 vectors of strings for: name, content and mimetypes, there is now a vector of `message_file_data` structs.

This doesn't break the way you add files, but rather breaks the way you read files you've added to a message.

## Code change checklist

- [x] I have ensured that all methods and functions are **fully documented** using doxygen style comments.
- [x] My code follows the [coding style guide](https://dpp.dev/coding-standards.html).
- [x] I tested that my change works before raising the PR.
- [x] I have ensured that I did not break any existing API calls.
- [x] I have not built my pull request using AI, a static analysis tool or similar without any human oversight.

2023-11-06 22:11 UTC, Jaskowicz1 commented
![image](https://github.com/brainboxdotcc/DPP/assets/46899449/14b621ea-9cec-4cf3-8ae7-2f2838fa7ccb)
![image](https://github.com/brainboxdotcc/DPP/assets/46899449/9481f9f4-98a2-45de-b28b-2638c77c615a)
This is proof of it still working!

2023-11-06 22:14 UTC, braindigitalis requested changes

2023-11-06 22:14 UTC, braindigitalis commented on src/dpp/cluster/appcommand.cpp
> +	for(message_file_data data : m.file_data) {
can't we just send the vector over to the function instead of splitting it into 3 like this? seems hacky to split it like this.

2023-11-07 08:15 UTC, Jaskowicz1 commented
Reverted to draft as more changes are required.

2023-11-07 08:41 UTC, Jaskowicz1 commented
No longer in draft, ready for review!

2023-11-08 01:06 UTC, merged